version: '3.8'

services:
  chi-app-1:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8080:8080"
    depends_on:
      - memcache
    restart: always
    networks:
      - app-network

  chi-app-2:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8081:8080"
    depends_on:
      - memcache
    restart: always
    networks:
      - app-network

  chi-app-3:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8082:8080"
    depends_on:
      - memcache
    restart: always
    networks:
      - app-network

  chi-app-4:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8083:8080"
    depends_on:
      - memcache
    restart: always
    networks:
      - app-network

  chi-app-5:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8084:8080"
    depends_on:
      - memcache
    restart: always
    networks:
      - app-network

  memcache:
    image: memcached:latest
    restart: always
    ports:
      - "11211:11211"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge