version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8080:8080"
    depends_on:
      - memcache
    restart: always
    networks:
      - app-network

  memcache:
    image: memcached:alpine
    restart: always
    ports:
      - "11211:11211"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge